liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/makeaneffort
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

